### ISSUE TITLE
Implement basic structures of ESM interpretation

### ISSUE THREAD

**Issue by h2oche** [es-meta/es-meta#3]
## TODO
- [ ] Define basic data structures(state, heap, value, ...) for interpretation.
- [ ] Implement basic interpretation class.
- [ ] Add tests for interpretation.

## ESM Abstract Syntax
Instruction
- Let
- Set
- If
- Return

Expression
- Number
- Boolean
- ReturnIfAbrupt
- Reference
- Record
- AbstractOperationCall
- AbstractMethodCall

## ESM State
...
